### ISSUE TITLE
Markdown 列表支持

### ISSUE THREAD

**Issue by Voleking** [sollrei/bitcron-template#1]
你好👋，很喜欢你的这个模板，但是貌似没有对于 [Markdown 列表](https://pi.bitcron.com/post/basic_markdown#toc_4)的支持，可否加上呢？

**Comment by sollrei** [comment]
![image](https://user-images.githubusercontent.com/1720881/30014933-31fe4a16-9181-11e7-9e20-4992c859b8de.png)
是指的文章里这样的展示样式么？

如果是的话可以：
主题 -> 克隆源码   到文件管理器里找 template -> style.scss 加
```scss
.markdown {
    ul,ol {
        padding-left: 40px;
    }
    ul {
        list-style-type: disc;
    }
    ol {
        list-style-type: decimal;
    }
}
```

或者
直接在 Dashboard -> 呈现 -> 嵌入模板里面加
```html
<style>
.markdown ul,
.markdown ol {
    padding-left: 40px;
}
.markdown ul {
    list-style-type: disc;
}
.markdown ol {
    list-style-type: decimal;
}
</style>
```

如果不是上面的意思的话再追问下吧(～￣▽￣)～
